databases:
  - name: rails_ec_db
    databaseName: rails_ec_db
    user: rails-ec-site
    region: singapore

services:
  - type: web
    name: rails-ec-site
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    # startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_ec_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

